### ISSUE TITLE
Broken link reports page does not load for more than 1500 broken links

### ISSUE THREAD

**Issue by ykhadilkar-rei** [datagovuk/ckanext-report#10]
Broken link reports page does not load if there are more than 1500 broken links for that organization. We are thinking of limiting number of records we push in JSON data to first 1000 broken links.  
What do you guys think? Any other way to optimize?

**Comment by ykhadilkar-rei** [comment]
Looks like our branch has bunch of updates. We are checking if that affected optimization.

**Comment by davidread** [comment]
I can't remember there being any limits like this. But our current record broken links on data.gov.uk is 655, so can't test easily.

I'm quite keen on having a default limit when displaying the report, since big reports can take seconds to render, which may not be what you want. Although it would be good to be able to click a button to see the full report in the browser if you want it. And I think the JSON stored should be the non-limited version, so that you can download a huge CSV/JSON if you really want to.
